In [1]:
import numpy as np
import pandas as pd


In [3]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
df=pd.read_csv("C:\\Users\\admin\\Downloads\\Telco-Customer-Churn.csv")
df.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   

      PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Electronic check          29.85         29.85    No  
1      Mailed check          56.95        1889.5    No  
2      Mailed check          53.85        108.15   Yes  

[3 rows x 21 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
obj=df.select_dtypes('object').columns
for i in obj:
    df[i]=LE.fit_transform(df[i])
from sklearn.preprocessing import StandardScaler
mm = StandardScaler()
s=mm.fit_transform(df.values)

In [13]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [16]:
from sklearn.model_selection import cross_val_score

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn_cv = KNeighborsClassifier(n_neighbors=12,)
knn_cv.fit(x,y)
cv_scores = cross_val_score(knn_cv, x, y, cv=5)
print(cv_scores)
print(np.mean(cv_scores))

[0.72675656 0.72249823 0.72249823 0.72088068 0.72585227]
0.7236971941738176


In [25]:
knn2 = KNeighborsClassifier()
param_grid = {
    'n_neighbors': np.arange(1, 25),
    'weights':['uniform','distance']
    }
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)
knn_gscv.fit(x, y)
print(knn_gscv.best_params_)
print(knn_gscv.best_score_)

{'n_neighbors': 24, 'weights': 'uniform'}
0.7310809366733337


In [24]:
knn_rscv= RandomizedSearchCV(knn2, param_distributions=param_grid, n_iter=20)
knn_rscv.fit(X,y)
print( knn_rscv.best_params_)
print( knn_rscv.best_score_)

NameError: name 'X' is not defined

In [23]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression(random_state=42)
log_reg.fit(X,y)
cv_scores=cross_val_score(log_reg,X,y,cv=5)
print(cv_scores)
print(np.mean(cv_scores))

[0.80170576 0.80028429 0.79374111 0.80654339 0.80440967]
0.8013368435206611


In [55]:
log_reg2=LogisticRegression()
param_grid={
    'penalty' : ['l1','l2'], 
    'C'       : np.logspace(-3,3,7),
    'solver'  : ['newton-cg', 'lbfgs', 'liblinear'],
}
log_reg_gscv=GridSearchCV(log_reg2,param_grid,cv=5)
log_reg_gscv.fit(X,y)
print(log_reg_gscv.best_params_)
print(log_reg_gscv.best_score_)

{'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}
0.8030415894516445


In [59]:
log_rscv= RandomizedSearchCV(log_reg2, param_distributions=param_grid, n_iter=20)
log_rscv.fit(X,y)
print( log_rscv.best_params_)
print( log_rscv.best_score_)

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.1}
0.8030415894516445


In [63]:
from sklearn.naive_bayes import GaussianNB
gg=GaussianNB()
gg.fit(X,y)
cv_scores=cross_val_score(gg,X,y,cv=5)
print(cv_scores)
print(np.mean(cv_scores))

[0.75266525 0.7583511  0.73897582 0.76031294 0.75248933]
0.7525588881441199


In [64]:
gg.get_params()

{'priors': None, 'var_smoothing': 1e-09}

In [67]:
param_grid = {
    'var_smoothing': np.logspace(0,-9, num=100)
}
gg2= GridSearchCV(estimator=GaussianNB(), param_grid=param_grid, verbose=1, cv=10, n_jobs=-1)
gg2.fit(X, y)
print(gg2.best_score_)
print(gg2.best_estimator_)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits
0.7868291736712789
GaussianNB(var_smoothing=0.0001232846739442066)


In [68]:
gg_rscv= RandomizedSearchCV(gg, param_distributions=param_grid, n_iter=20)
gg_rscv.fit(X,y)
print( gg_rscv.best_params_)
print( gg_rscv.best_score_)

{'var_smoothing': 2.310129700083158e-05}
0.7680589129135869


In [69]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X,y)
cv_scores=cross_val_score(dt,X,y,cv=5)
print(cv_scores)
print(np.mean(cv_scores))

[0.73916134 0.72778962 0.7197724  0.70128023 0.74466572]
0.7265338618834298


In [71]:
param_grid={
    'max_depth':range(5,20),
    'min_samples_leaf':[1,10],
    'criterion':['ginni','entropy']
}
dt2=GridSearchCV(estimator=DecisionTreeClassifier(),param_grid=param_grid,verbose=1,cv=10,n_jobs=-1)
dt2.fit(X,y)
print(dt2.best_score_)
print(dt2.best_estimator_)

Fitting 10 folds for each of 60 candidates, totalling 600 fits
0.7891087708521919
DecisionTreeClassifier(criterion='entropy', max_depth=5)


In [72]:
dt_rscv= RandomizedSearchCV(dt, param_distributions=param_grid, n_iter=20)
dt_rscv.fit(X,y)
print( dt_rscv.best_params_)
print( dt_rscv.best_score_)

{'min_samples_leaf': 10, 'max_depth': 7, 'criterion': 'entropy'}
0.7862628535841419


In [19]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X,y)
cv_scores=cross_val_score(svc,X,y,cv=5)
print(cv_scores)
print(np.mean(cv_scores))

[0.73418621 0.73418621 0.73470839 0.73399716 0.73399716]
0.7342150252598014


In [17]:
from sklearn.model_selection import train_test_split
x_tr,x_ts,y_tr,y_ts=train_test_split(X,y,test_size=0.25,random_state=42)

In [20]:
param_grid = {
    'C': [0.1,1,10,100], 
    'gamma': [1,0.1,0.001,0.001],
    'kernel': ['rbf', 'poly', 'sigmoid']
    }
svm2=GridSearchCV(estimator=SVC(),param_grid=param_grid,cv=10,n_jobs=-1)
svm2.fit(x_tr,y_tr)
print(svm2.best_score_)
print(svm2.best_estimator_)

Fitting 10 folds for each of 27 candidates, totalling 270 fits


In [ ]:
param_grid = {
    'C': [0.1,1, 10, 100], 
    'gamma': [1,0.1,0.01,0.001],
    'kernel': ['rbf', 'poly', 'sigmoid']
    }
svm_rscv= RandomizedSearchCV(svc, param_distributions=param_grid, n_iter=20)
svm_rscv.fit(X,y)
print( svm_rscv.best_params_)
print( svm_rscv.best_score_)